// Todo constant
export const FETCH_TODOS = "FETCH_TODOS"
export const FETCH_TODOS_PENDING = "FETCH_TODOS_PENDING"
export const FETCH_TODOS_FULFILLED = "FETCH_TODOS_FULFILLED"
export const FETCH_TODOS_REJECTED = "FETCH_TODOS_REJECTED"

// Auth constant
export const FETCH_USER = "FETCH_USER"
export const FETCH_USER_PENDING = 'FETCH_USER_PENDING'
export const FETCH_USER_FULFILLED = 'FETCH_USER_FULFILLED'
export const FETCH_USER_REJECTED = 'FETCH_USER_REJECTED'

// Redux Promise Middleware constant
export const FETCH_DATA = 'FETCH_DATA'
export const FETCH_DATA_PENDING = 'FETCH_DATA_PENDING'
export const FETCH_DATA_FULFILLED = 'FETCH_DATA_FULFILLED'
export const FETCH_DATA_REJECTED = 'FETCH_DATA_REJECTED'

export const FETCH_POSTS = 'FETCH_POSTS'
export const FETCH_POSTS_PENDING = 'FETCH_POSTS_PENDING'
export const FETCH_POSTS_FULFILLED = 'FETCH_POSTS_FULFILLED'
export const FETCH_POSTS_REJECTED = 'FETCH_POSTS_REJECTED'
